// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mlkukralmzrwspyjncpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sa3VrcmFsbXpyd3NweWpuY3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyOTI4MDYsImV4cCI6MjA5Mzg2ODgwNn0.DgCVa-Ws8geTHjoQeN7rfYwT9vq_I8jIA8640j-ho4Q";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);